#ifndef tracklist_peg
#define tracklist_peg


#ifndef PEG_STRUCT
#define PEG_STRUCT
typedef struct {
  float min;
  float max;
  float default_value;
  char toggled;
  char integer;
  char logarithmic;
} peg_data_t;
#endif

/* <http://lab-audio.googlecode.com/svn/trunk/plugins/tracklist> */

static const char peg_uri[] = "http://lab-audio.googlecode.com/svn/trunk/plugins/tracklist";

enum peg_port_enum {
  peg_n_ports
};

static const peg_data_t peg_ports[] = {
};


#endif /* tracklist_peg */
